export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const LOAD_MY_PARTNERS_SUCCESS = 'LOAD_MY_PARTNERS_SUCCESS';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const ADD_TODO_ITEM_SUCCESS = 'ADD_TODO_ITEM_SUCEES';
export const LOAD_PLANNER_TODO_SUCCESS = 'LOAD_PLANNER_TODO_SUCCESS';
export const ADD_PLANNER_TODO_ITEM_SUCCESS = 'ADD_PLANNER_TODO_ITEM_SUCCESS';
